apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: button0-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"  # Ensure backend is deployed after postgres
spec:
  project: default
  source:
    repoURL: https://github.com/YonatanK0510/button0.git
    targetRevision: master
    path: helm/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: button0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true