apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: button0-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YonatanK0510/button0.git
    targetRevision: master
    path: helm/frontend
    helm:
      values: |
        backend:
          service:
            name: button0-backend
            port: 8000

        ingress:
          enabled: true
          className: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:186582695522:certificate/2534f2ef-c25b-43b8-bb58-486d633f4551
            alb.ingress.kubernetes.io/ssl-redirect: "443"
          hosts:
            - host: dev.yk-loh7.online
              paths:
                - path: /api
                  pathType: Prefix
                - path: /
                  pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: button0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
