apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: button0-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 18.2.6
    helm:
      releaseName: button0-postgresql
      values: |
        global:
          postgresql:
            auth:
              database: button0
              username: button0
        primary:
          persistence:
            enabled: true
            size: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: button0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
