apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: button0-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:YonatanK0510/button0-gitops.git
    targetRevision: master
    path: environments/dev/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
